name: Gerar Keystore Temp - Melhor Dia

on:
  workflow_dispatch:

jobs:
  gerar:
    runs-on: ubuntu-latest
    steps:
      - name: Gerar keystore fixa alias android
        run: |
          keytool -genkeypair -v -keystore android.keystore -alias android -keyalg RSA -keysize 2048 -validity 10000 -storepass gkdmelhordia2026 -keypass gkdmelhordia2026 -dname "CN=GKD, OU=IT, O=GKD, L=City, ST=State, C=BR"
          base64 -w 0 android.keystore > android.keystore.b64
          echo "Tamanho do base64:"
          wc -c android.keystore.b64

      - name: Publicar keystore em base64
        uses: actions/upload-artifact@v4
        with:
          name: melhordia-keystore-b64
          path: android.keystore.b64

